import React, { useState } from 'react';
import { Activity, Bot, FileCheck, Key, LayoutDashboard, ListChecks, Menu, ShieldCheck, X } from 'lucide-react';
import type { UserSession } from '../types/veriflow';

interface WorkspaceNavbarProps { userSession: UserSession; current: string; onNavigate: (path: string) => void; onOpenAttestation: () => void; onDisconnect: () => void }
export const WorkspaceNavbar: React.FC<WorkspaceNavbarProps> = ({ userSession, current, onNavigate, onOpenAttestation, onDisconnect }) => {
  const [mobileOpen, setMobileOpen] = useState(false);
  const links = [
    ['/app/dashboard', 'Dashboard', LayoutDashboard], ['/app/verify', 'Verify', FileCheck], ['/app/history', 'History', ShieldCheck], ['/app/requests', 'Requests', ListChecks], ['/app/developer', 'Developer', Key], ['/app/assistant', 'Assistant', Bot],
  ] as const;
  return <header className="sticky top-0 z-40 bg-slate-950/95 backdrop-blur-xl border-b border-slate-800/80"><div className="max-w-[1600px] mx-auto px-4 h-16 flex items-center gap-4"><button onClick={() => onNavigate('/app/dashboard')} className="flex items-center gap-2 text-white font-black shrink-0"><span className="w-8 h-8 rounded-xl bg-gradient-to-br from-teal-400 to-cyan-500 flex items-center justify-center"><ShieldCheck className="w-4 h-4 text-slate-950" /></span>VeriFlow<span className="text-teal-400">/app</span></button><nav className="hidden xl:flex items-center gap-1 flex-1">{links.map(([path, label, Icon]) => <button key={path} onClick={() => onNavigate(path)} aria-current={current === path ? 'page' : undefined} className={`px-3 py-2 rounded-lg text-xs font-bold flex items-center gap-1.5 ${current === path ? 'bg-teal-500/15 text-teal-300 border border-teal-500/30' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}><Icon className="w-3.5 h-3.5" />{label}</button>)}</nav><div className="hidden lg:flex items-center gap-2 text-[10px] font-mono"><button onClick={onOpenAttestation} className="px-2.5 py-1.5 rounded-lg bg-slate-900 border border-emerald-500/30 text-emerald-300"><Activity className="w-3 h-3 inline mr-1 animate-pulse" />Flare Coston2 ONLINE</button><span className="px-2.5 py-1.5 rounded-lg bg-slate-900 border border-teal-500/30 text-teal-300">Intel SGX DCAP QUOTE VERIFIED</span></div><div className="flex items-center gap-2 ml-auto"><span className="hidden sm:inline px-2.5 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-xs font-mono text-slate-300">{userSession.isConnected ? `${userSession.address.slice(0, 6)}…${userSession.address.slice(-4)}` : 'SIWE disconnected'}</span>{userSession.isConnected && <button onClick={onDisconnect} className="text-[10px] text-slate-500 hover:text-rose-300">Disconnect</button>}<button onClick={() => setMobileOpen(value => !value)} aria-label="Toggle workspace navigation" className="xl:hidden p-2 rounded-lg bg-slate-900 border border-slate-800">{mobileOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}</button></div></div>{mobileOpen && <nav className="xl:hidden px-4 pb-4 grid grid-cols-2 sm:grid-cols-3 gap-2">{links.map(([path,label,Icon]) => <button key={path} onClick={() => { onNavigate(path); setMobileOpen(false); }} className={`p-3 rounded-xl border text-xs flex items-center gap-2 ${current === path ? 'bg-teal-500/10 border-teal-500/30 text-teal-300' : 'bg-slate-900 border-slate-800 text-slate-400'}`}><Icon className="w-4 h-4" />{label}</button>)}</nav>}</header>;
};
